# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
#targets:
#  $default:
#    builders:
#      rua_generator|pre_builder:
#        enabled: true
#        generate_for:
#          exclude: ['**.g.dart', 'lib/generated/**']
builders:
  deflect_generator:
    import: 'package:deflect_generator/src/builder.dart'
    builder_factories: ['defaultBuilder']
    build_extensions: { '.dart': ['.g.part'] }
    auto_apply: dependents
    build_to: cache